export const CREATE_PROPERTY = "CREATE_PROPERTY";
export const EDIT_PROPERTY = "EDIT_PROPERTY";
export const FETCH_PROPERTY = "FETCH_PROPERTY";
export const FETCH_PROPERTIES = "FETCH_PROPERTIES";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
